### ISSUE TITLE
403 on CodeSearch

### ISSUE THREAD

**Issue by zanussbaum** [amazon-science/CodeSage#6]
hey all thanks for the great package! 

I'm getting a 403 when trying to download CodeSearch following the instructions here: https://github.com/amazon-science/CodeSage/blob/main/data/nl2code/README.md?plain=1#L8

**Comment by wasiahmad** [comment]
We have shared the NL2Code search datasets here: https://drive.google.com/drive/folders/1_hy3Z7ZRDtoY11Auo1O0dUgDwjTxwAaX

cc: @Dejiao2018
